[package]
name = "makepad-live-macros-impl"
version = "0.2.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad live macros implementation"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5" 

[dependencies.makepad-shader-compiler] 
path="../../shader_compiler"
