[package]
name = "bare_example"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[dependencies]

[dependencies.bare_example_app]
path="./app"

[dependencies.makepad-shader-compiler]
path="../../render/shader_compiler"
version="0.1"